[package]
name = "resin-wifi-connect"
version = "0.1.0"
authors = ["Joe Roberts <joe@resin.io>"]
description = "Wi-Fi credentials configuration tool"

[dependencies]
clippy = {version = "*", optional = true}
network_manager = { git = "https://github.com/resin-io-modules/network_manager", branch = "master" }
clap = "*"
iron = "*"
staticfile = "*"
mount = "*"
router = "*"
serde_json = "*"
persistent = "*"
params = "*"
log = "*"
env_logger = "*"

[profile.release]
lto = true
